### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RGarciaLago**
Creating an MGL file with "SG1000" as a setname to help new users with core awareness and be able to set separate configs from the base core.

### CODE REVIEW

**Comment by sorgelig** [comment]
SG1000 is supported in 2 cores: ColecoVision and SMS.
So i suggest to use SG1000SV setname here.

**Comment by RGarciaLago** [comment]
Good idea! I just updated the setname to "SG1000SV". Thank you.

**Comment by RGarciaLago** [comment]
@sorgelig Out of curiosity what does SV mean for the setname?

**Comment by sorgelig** [comment]
mistyped :) Should be CV (ColecoVision).

**Comment by RGarciaLago** [comment]
@sorgelig After speaking with @Kitrinx it was decided to undo this PR and remove the MGL as her preference is to improve the SMS core. Fortunately we haven't gone live with this change so no users have the MGL as part of the official distrubtion thanks to @theypsilon wise decision to wait.

We won't submit an MGL for the SG-1000 until the SMS is the definitive way to play SG-1000 games. Thank you very much for your time, Alexey!

**Comment by sorgelig** [comment]
so, do you want me to revert this commit?

**Comment by RGarciaLago** [comment]
Yes, please. Sorry for the trouble.

**Comment by sorgelig** [comment]
ok. done.

**Pull request merged**
